version: 2.1

orbs:
  android: circleci/android@2.0.0
  katalon-studio: katalon/katalon-studio@23.0.11

jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: medium
      tag: 2022.03.1
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run Tests
          command: ./gradlew runTests
      - store_artifacts:
          path: ~/project/resources