version: 2.1

orbs:
  android: circleci/android@2.0.0
  katalon-studio: katalon/katalon-studio@23.0.11

jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: medium
      tag: 2022.03.1
    working_directory: ~/project
    steps:
      - checkout
      - android/create-avd:
          avd-name: Android-Emulator
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator:
          avd-name: Android-Emulator
          #post-emulator-launch-assemble-command: 'flutter build apk --debug'
          restore-gradle-cache-find-args: ./android -name 'build.gradle'
      - store_artifacts:
          path: ~/project/resources