version: 2.1

orbs:
  android: circleci/android@2.0.0
  # Refer to this link to setup Slack channels: https://github.com/CircleCI-Public/slack-orb/wiki/Setup
  # Setup slack app also:  https://github.com/CircleCI-Public/slack-orb/issues/207#issuecomment-731219733
  slack: circleci/slack@4.9.3

jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: medium
      tag: 2022.03.1
    working_directory: ~/project
    steps:
      - checkout
  appium_server:
    steps:
      - run:
          name: Install Appium
          command: npm install -g appium
      - run:
          name: Start Appium
          command: cd ; appium
          background: true
  android_emulator:
    steps:
      - android/create-avd:
          avd-name: Android-Emulator
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator:
          avd-name: Android-Emulator
          post-emulator-launch-assemble-command: 'ls' #workaround to not run androidAssembleDebugTest task
  manage_apk:
    steps:
      - run:
          name: Download apk
          command: cd ~/project/resources/apk && { curl -L -O https://output.circle-artifacts.com/output/job/acb4a6fe-51cb-4bcc-976c-f9a2c047ea6e/artifacts/0/~/project/build/app/outputs/flutter-apk/app-debug.apk ; cd -; }
      - run:
          name: Install APK
          command: adb install ~/project/resources/apk/app-debug.apk
  android_testing:
    steps:
      - run:
          name: Run Tests
          command: ./gradlew runTests
      - store_artifacts:
          path: ~/project/resources
  notifications:
    steps:
      - slack/notify:
          event: always
          template: basic_success_1

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master