version: 2.1

orbs:
  flutter-orb: circleci/flutter@1.0.1
  android: circleci/android@2.0.0
  katalon-studio: katalon/katalon-studio@23.0.11

jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: medium
      tag: 2022.03.1
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Appium
          command: npm install appium@1.14.0
      - run:
          name: Start Appium
          command: cd ; appium
          background: true
      - run:
         name: Wait Until Appium Boot
         command: sleep 30
      - android/create-avd:
          avd-name: Android-Emulator
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator:
          avd-name: Android-Emulator
          post-emulator-launch-assemble-command: 'ls' #workaround to not run androidAssembleDebugTest task
      - run:
          name: Install APK
          command: adb install ~/project/resources/apk/app-debug.apk
      - run:
          name: Run Tests
          command: ls
      - store_artifacts:
          path: ~/project/resources